### ISSUE TITLE
Update to use the new Gleam build tool

### ISSUE THREAD

**Issue by lpil** [davecaos/benetnasch#1]
Hello! Gleam has moved away from rebar3. It would be grand to have this library using the new build tool that is included with the `gleam` binary.

**Comment by davecaos** [comment]
Hi @lpil 👋 
It's done, sorry sorry for taking so long, I had to do some minimal changes but it run like a charm 
Thanks for the work u are doing with gleam 🙇

**Comment by lpil** [comment]
Fab! Thank you
